name: Cypress Tests CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  schedule:
    # Executar diariamente às 9 AM (horário UTC)
    - cron: '0 9 * * *'

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox]
        node-version: [20.x]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test
        env:
          CI: true
          BROWSER: ${{ matrix.browser }}

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ matrix.browser }}
          path: cypress/reports/
          retention-days: 30

      - name: Upload screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots/

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos/

      - name: Generate HTML Report
        if: always()
        run: npm run posttest

      - name: Deploy reports to GitHub Pages (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/mochawesome-report/

  test-status:
    runs-on: ubuntu-latest
    needs: cypress-tests
    if: always()
    steps:
      - name: Set status based on test results
        run: |
          if [ "${{ needs.cypress-tests.result }}" == "success" ]; then
            echo "✅ All tests passed!"
            exit 0
          else
            echo "❌ Some tests failed"
            exit 1
          fi
